// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqwMdIN9tuKtdOvqQzoeZH2cy-6SkAIiQ',
    appId: '1:479784229163:web:a37a7b248a27053335cd6e',
    messagingSenderId: '479784229163',
    projectId: 'test-91ace',
    authDomain: 'test-91ace.firebaseapp.com',
    storageBucket: 'test-91ace.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe9ceDg8t6tqDmcWx5AhlZDK2usE1isZ0',
    appId: '1:479784229163:android:b2b847bd05c760ea35cd6e',
    messagingSenderId: '479784229163',
    projectId: 'test-91ace',
    storageBucket: 'test-91ace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCem4tPVZPKdtUzQrWaypqTJpsyQvhNB1o',
    appId: '1:479784229163:ios:9ffc095ac9db0b4435cd6e',
    messagingSenderId: '479784229163',
    projectId: 'test-91ace',
    storageBucket: 'test-91ace.appspot.com',
    iosBundleId: 'com.example.sportwaveBlog',
  );
}
